name: React CI/CD to Render

on:
  push:
    branches:
      - main  # or 'master' depending on your repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18  # or whatever your project uses

    - name: Install dependencies
      run: npm install

    - name: Run tests (optional)
      run: npm test --if-present

    - name: Build React app
      run: npm run build

    - name: Trigger Render deploy hook
      run: |
        curl -X POST https://api.render.com/deploy/srv-d13ajgp5pdvs73dh94kg?key=NmnNhQ7TT-k
